const prefix = "https://openstore.obabyball.com"

export const iconUrls = {
  tabHot: prefix + '/ui_v1/icon/tab-hot-v1.svg',
  tabOfficial: prefix + '/ui_v1/icon/tab-official-v1.svg',
  tabUnofficial: prefix + '/ui_v1/icon/tab-unofficial-v2.svg',
  tabSearch: prefix + '/ui_v1/icon/tab-search-v1.svg',
  tabArrow: prefix + '/ui_v1/icon/tab-arrow-v1.svg',
  barAdd: prefix + '/ui_v1/icon/bar-add-v1.svg',
  barClose: prefix + '/ui_v1/icon/add-close-v2.svg',
  barHome: prefix + '/ui_v1/icon/bar-home-v1.svg',
  barLook: prefix + '/ui_v1/icon/bar-look-v1.svg',
  barTeam: prefix + '/ui_v1/icon/bar-team-v1.svg',
  barMine: prefix + '/ui_v1/icon/bar-mine-v1.svg',
  barHomeGrey: prefix + '/ui_v1/icon/bar-home-grey-v1.svg',
  barLookGrey: prefix + '/ui_v1/icon/bar-look-grey-v1.svg',
  barTeamGrey: prefix + '/ui_v1/icon/bar-team-grey-v1.svg',
  barMineGrey: prefix + '/ui_v1/icon/bar-mine-grey-v1.svg',
  addCalendar: prefix + '/ui_v1/icon/add-calendar-v1.png',
  addStartTime: prefix + '/ui_v1/icon/add-start-time-v1.png',
  addEndTime: prefix + '/ui_v1/icon/add-end-time-v1.png',
  addLocation: prefix + '/ui_v1/icon/add-location-v1.png',
  addJoinNum: prefix + '/ui_v1/icon/add-join-num-v1.png',
  addStartAge: prefix + '/ui_v1/icon/add-up-v1.png',
  addEndAge: prefix + '/ui_v1/icon/add-down-v1.png',
  addCost: prefix + '/ui_v1/icon/add-cost-v1.png',
  addUpload: prefix + '/ui_v1/icon/add-upload-v1.svg',
  descUnofficialTag: prefix + '/ui_v1/icon/desc-unofficial-tag-v1.svg',
  descOfficialTag: prefix + '/ui_v1/icon/desc-official-tag-v1.svg',
  descClock: prefix + '/ui_v1/icon/desc-clock-v1.svg',
  descLocation: prefix + '/ui_v1/icon/desc-location-v1.svg',
  cityLocation: prefix + '/ui_v1/icon/city-location-v1.svg',
  addTeamUpload: prefix + '/ui_v1/icon/add-team-upload-v1.svg',
  addTeamName: prefix + '/ui_v1/icon/add-team-name-v1.svg',
  addTeamIntro: prefix + '/ui_v1/icon/add-team-intro-v1.svg',
  addTeamLocation: prefix + '/ui_v1/icon/add-team-location-v1.svg',
  addTeamAddress: prefix + '/ui_v1/icon/add-team-address-v1.svg',
  mineArrowDown: prefix + '/ui_v1/icon/mine-arrow-down-v1.svg',
  mineTeam: prefix + '/ui_v1/icon/mine-team-v1.svg',
  mineApply: prefix + '/ui_v1/icon/mine-apply-v1.svg',
  mineIn: prefix + '/ui_v1/icon/mine-in-v1.svg',
  mineOfficial: prefix + '/ui_v1/icon/tab-official-v1.svg',
  mineUnofficial: prefix + '/ui_v1/icon/tab-unofficial-v2.svg',
  addActionUnofficial: prefix + '/ui_v1/icon/tab-unofficial-v2.svg',
  addActionOfficial: prefix + '/ui_v1/icon/tab-official-v1.svg',
  mineReferee: prefix + '/ui_v1/icon/mine-referee-v1.svg',
  matchCardClock: prefix + '/ui_v1/icon/match-card-clock-v1.svg',
  matchCardLocation: prefix + '/ui_v1/icon/match-card-location-v1.svg',
  descSuccess:prefix + '/ui_v1/icon/success.svg',
}

export const imgUrls = {
  bannerImg: prefix + "/ui_v1/img/banner-img-v1.png",
  mineLightImg: prefix + "/ui_v1/img/mine-light-img-v1.svg",
  enListBgImg: prefix + "/ui_v1/img/enlist-bg-img-v2.svg",
  enListAvatarOutlineImg: prefix + "/ui_v1/img/enlist-avatar-outline-v1.svg",
  detailTeamBgImg: prefix + "/ui_v1/img/detail-team-bg-img-v1-compress-v2.png",
  matchCardBgImage: prefix + "/ui_v1/img/match-card-bg-ball-v1.png"
}

